#!/bin/sh
LOGFILE=/tmp/mikey.log
while true
do
  HEADERS="$(mktemp)"

  # Get an event. The HTTP request will block until one is received
  EVENT_DATA=$(curl -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")

  # Extract request ID by scraping response headers received above
  REQUEST_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

  # Run the handler function from the script
  RESPONSE=$(Rscript ${LAMBDA_TASK_ROOT}/runtime.R $EVENT_DATA)

  # Were we successful?
  RESPONSE_CODE=$?
  if [ $RESPONSE_CODE = 0 ]; then
    OUT="response"
  else
    OUT="error"
  fi

  # Send the response
  curl -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/${REQUEST_ID}/${OUT}" -d "$RESPONSE"
done
